"use client";
import "@/app/globals.css";
import { TerminalContextProvider } from "react-terminal";

// const geistSans = localFont({
//   src: "./fonts/GeistVF.woff",
//   variable: "--font-geist-sans",
//   weight: "100 900",
// });
// const geistMono = localFont({
//   src: "./fonts/GeistMonoVF.woff",
//   variable: "--font-geist-mono",
//   weight: "100 900",
// });
// export const metadata = {
//   title: "Emirhan Çöpoğlu",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        //${geistSans.variable} ${geistMono.variable}
        className={` antialiased`}
      >
        <TerminalContextProvider> {children}</TerminalContextProvider>
      </body>
    </html>
  );
}
